Repository algosup/2024-2025-project-3-quickest-path-team-4, pull requests merged in 2025-01, with the labels that each got.

#2 DOC: Adding basic documents for contribution, license and miscellaneous. Additionally added naming convention file.
  .gitignore
  CONTRIBUTING.md
  LICENSE
  README.md
  technicalSpecification/namingConventions.md
Labels: documentation

#5 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: bug

#12 Qa
  qualityAssurance/images/TestSample.png
  qualityAssurance/testCases.md
  qualityAssurance/testFile/allIsolatedNodes.csv
  qualityAssurance/testFile/cycleDetection.csv
  qualityAssurance/testFile/dataTest.csv
  qualityAssurance/testFile/duplicateRows.csv
  qualityAssurance/testFile/edgesTest.csv
  qualityAssurance/testFile/empty.csv
  qualityAssurance/testFile/equalPathsGraph.csv
  qualityAssurance/testFile/invalidFormat.csv
  qualityAssurance/testFile/missingFields.csv
  qualityAssurance/testFile/negativeTime.csv
  qualityAssurance/testFile/notFullyConnected.csv
  qualityAssurance/testFile/selfLoopsTest.csv
  qualityAssurance/testFile/textFile.txt
  qualityAssurance/testFile/wrongType.csv
  qualityAssurance/testPlan.md
  qualityAssurance/testing/algo.cpp
  qualityAssurance/testing/dataVerif.cpp
Labels: documentation, help wanted
